// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/focus_hub.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FocusHubPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHubPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FocusHub
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    dynamic raw,
  );

  @protected
  FocusHub
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    dynamic raw,
  );

  @protected
  FocusHub
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    dynamic raw,
  );

  @protected
  FocusHub
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  CalendarDay dco_decode_calendar_day(dynamic raw);

  @protected
  CalendarMonth dco_decode_calendar_month(dynamic raw);

  @protected
  DayTodos dco_decode_day_todos(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImportSummary dco_decode_import_summary(dynamic raw);

  @protected
  List<CalendarDay> dco_decode_list_calendar_day(dynamic raw);

  @protected
  List<DayTodos> dco_decode_list_day_todos(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RewardView> dco_decode_list_reward_view(dynamic raw);

  @protected
  List<ScheduledAlert> dco_decode_list_scheduled_alert(dynamic raw);

  @protected
  List<SessionAlert> dco_decode_list_session_alert(dynamic raw);

  @protected
  List<TodoView> dco_decode_list_todo_view(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  RewardView dco_decode_reward_view(dynamic raw);

  @protected
  ScheduledAlert dco_decode_scheduled_alert(dynamic raw);

  @protected
  SessionAlert dco_decode_session_alert(dynamic raw);

  @protected
  StatsView dco_decode_stats_view(dynamic raw);

  @protected
  TimeZoneView dco_decode_time_zone_view(dynamic raw);

  @protected
  TimerView dco_decode_timer_view(dynamic raw);

  @protected
  TodoView dco_decode_todo_view(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  YearMonth dco_decode_year_month(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  FocusHub
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    SseDeserializer deserializer,
  );

  @protected
  FocusHub
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    SseDeserializer deserializer,
  );

  @protected
  FocusHub
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    SseDeserializer deserializer,
  );

  @protected
  FocusHub
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  CalendarDay sse_decode_calendar_day(SseDeserializer deserializer);

  @protected
  CalendarMonth sse_decode_calendar_month(SseDeserializer deserializer);

  @protected
  DayTodos sse_decode_day_todos(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImportSummary sse_decode_import_summary(SseDeserializer deserializer);

  @protected
  List<CalendarDay> sse_decode_list_calendar_day(SseDeserializer deserializer);

  @protected
  List<DayTodos> sse_decode_list_day_todos(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RewardView> sse_decode_list_reward_view(SseDeserializer deserializer);

  @protected
  List<ScheduledAlert> sse_decode_list_scheduled_alert(
    SseDeserializer deserializer,
  );

  @protected
  List<SessionAlert> sse_decode_list_session_alert(
    SseDeserializer deserializer,
  );

  @protected
  List<TodoView> sse_decode_list_todo_view(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  RewardView sse_decode_reward_view(SseDeserializer deserializer);

  @protected
  ScheduledAlert sse_decode_scheduled_alert(SseDeserializer deserializer);

  @protected
  SessionAlert sse_decode_session_alert(SseDeserializer deserializer);

  @protected
  StatsView sse_decode_stats_view(SseDeserializer deserializer);

  @protected
  TimeZoneView sse_decode_time_zone_view(SseDeserializer deserializer);

  @protected
  TimerView sse_decode_timer_view(SseDeserializer deserializer);

  @protected
  TodoView sse_decode_todo_view(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  YearMonth sse_decode_year_month(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    FocusHub self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    FocusHub self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    FocusHub self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    FocusHub self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_calendar_day(CalendarDay self, SseSerializer serializer);

  @protected
  void sse_encode_calendar_month(CalendarMonth self, SseSerializer serializer);

  @protected
  void sse_encode_day_todos(DayTodos self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_import_summary(ImportSummary self, SseSerializer serializer);

  @protected
  void sse_encode_list_calendar_day(
    List<CalendarDay> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_day_todos(List<DayTodos> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reward_view(
    List<RewardView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scheduled_alert(
    List<ScheduledAlert> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_alert(
    List<SessionAlert> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_todo_view(List<TodoView> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_reward_view(RewardView self, SseSerializer serializer);

  @protected
  void sse_encode_scheduled_alert(
    ScheduledAlert self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_alert(SessionAlert self, SseSerializer serializer);

  @protected
  void sse_encode_stats_view(StatsView self, SseSerializer serializer);

  @protected
  void sse_encode_time_zone_view(TimeZoneView self, SseSerializer serializer);

  @protected
  void sse_encode_timer_view(TimerView self, SseSerializer serializer);

  @protected
  void sse_encode_todo_view(TodoView self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_year_month(YearMonth self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHubPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_focus_hub_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHubPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHubPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_focus_hub_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHubPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
