// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/focus_hub.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1454161223;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_focus_hub',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiFocusHubFocusHubAddReward({
    required FocusHub that,
    required String name,
  });

  void crateApiFocusHubFocusHubAddTodo({
    required FocusHub that,
    required String date,
    required String text,
  });

  String? crateApiFocusHubFocusHubBackgroundPath({required FocusHub that});

  CalendarMonth crateApiFocusHubFocusHubCalendarMonth({
    required FocusHub that,
    required int year,
    required int month,
    required String selectedDate,
  });

  void crateApiFocusHubFocusHubClearBackground({required FocusHub that});

  String crateApiFocusHubFocusHubClockText({required FocusHub that});

  String crateApiFocusHubFocusHubDataFile({required FocusHub that});

  void crateApiFocusHubFocusHubDeleteReward({
    required FocusHub that,
    required int index,
  });

  void crateApiFocusHubFocusHubDeleteTodo({
    required FocusHub that,
    required String date,
    required int index,
  });

  String crateApiFocusHubFocusHubExportJson({required FocusHub that});

  List<DayTodos> crateApiFocusHubFocusHubHistoryBefore({
    required FocusHub that,
    required String date,
  });

  ImportSummary crateApiFocusHubFocusHubImportJson({
    required FocusHub that,
    required String json,
  });

  String? crateApiFocusHubFocusHubLoadWarning({required FocusHub that});

  FocusHub crateApiFocusHubFocusHubOpen({required String dataDir});

  void crateApiFocusHubFocusHubResetTimer({required FocusHub that});

  List<RewardView> crateApiFocusHubFocusHubRewards({required FocusHub that});

  void crateApiFocusHubFocusHubSave({required FocusHub that});

  void crateApiFocusHubFocusHubSetBackground({
    required FocusHub that,
    required String fileName,
    required List<int> bytes,
  });

  void crateApiFocusHubFocusHubSetRewardCompleted({
    required FocusHub that,
    required int index,
    required bool completed,
  });

  void crateApiFocusHubFocusHubSetTimeZone({
    required FocusHub that,
    int? offsetHours,
  });

  void crateApiFocusHubFocusHubSetTimerSettings({
    required FocusHub that,
    required int workSecs,
    required int breakSecs,
    required int loops,
  });

  void crateApiFocusHubFocusHubSetTodoCompleted({
    required FocusHub that,
    required String date,
    required int index,
    required bool completed,
  });

  StatsView crateApiFocusHubFocusHubStats({required FocusHub that});

  List<SessionAlert> crateApiFocusHubFocusHubTick({required FocusHub that});

  TimeZoneView crateApiFocusHubFocusHubTimeZone({required FocusHub that});

  TimerView crateApiFocusHubFocusHubTimerView({required FocusHub that});

  List<TodoView> crateApiFocusHubFocusHubTodosFor({
    required FocusHub that,
    required String date,
  });

  List<SessionAlert> crateApiFocusHubFocusHubToggleTimer({
    required FocusHub that,
  });

  List<ScheduledAlert> crateApiFocusHubFocusHubUpcomingAlerts({
    required FocusHub that,
  });

  Future<void> crateApiSimpleInitApp();

  String crateApiFocusHubLongDate({required String date});

  YearMonth crateApiFocusHubMonthOf({required String date});

  YearMonth crateApiFocusHubShiftMonth({
    required int year,
    required int month,
    required int delta,
  });

  String crateApiFocusHubTodayDate();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FocusHub;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FocusHub;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_FocusHubPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiFocusHubFocusHubAddReward({
    required FocusHub that,
    required String name,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubAddRewardConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubAddRewardConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_add_reward",
        argNames: ["that", "name"],
      );

  @override
  void crateApiFocusHubFocusHubAddTodo({
    required FocusHub that,
    required String date,
    required String text,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubAddTodoConstMeta,
        argValues: [that, date, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubAddTodoConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_add_todo",
        argNames: ["that", "date", "text"],
      );

  @override
  String? crateApiFocusHubFocusHubBackgroundPath({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubFocusHubBackgroundPathConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubBackgroundPathConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_background_path",
        argNames: ["that"],
      );

  @override
  CalendarMonth crateApiFocusHubFocusHubCalendarMonth({
    required FocusHub that,
    required int year,
    required int month,
    required String selectedDate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_i_32(year, serializer);
          sse_encode_u_32(month, serializer);
          sse_encode_String(selectedDate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_calendar_month,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubCalendarMonthConstMeta,
        argValues: [that, year, month, selectedDate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubCalendarMonthConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_calendar_month",
        argNames: ["that", "year", "month", "selectedDate"],
      );

  @override
  void crateApiFocusHubFocusHubClearBackground({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubClearBackgroundConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubClearBackgroundConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_clear_background",
        argNames: ["that"],
      );

  @override
  String crateApiFocusHubFocusHubClockText({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubFocusHubClockTextConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubClockTextConstMeta =>
      const TaskConstMeta(debugName: "FocusHub_clock_text", argNames: ["that"]);

  @override
  String crateApiFocusHubFocusHubDataFile({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubFocusHubDataFileConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubDataFileConstMeta =>
      const TaskConstMeta(debugName: "FocusHub_data_file", argNames: ["that"]);

  @override
  void crateApiFocusHubFocusHubDeleteReward({
    required FocusHub that,
    required int index,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_u_32(index, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubDeleteRewardConstMeta,
        argValues: [that, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubDeleteRewardConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_delete_reward",
        argNames: ["that", "index"],
      );

  @override
  void crateApiFocusHubFocusHubDeleteTodo({
    required FocusHub that,
    required String date,
    required int index,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          sse_encode_u_32(index, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubDeleteTodoConstMeta,
        argValues: [that, date, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubDeleteTodoConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_delete_todo",
        argNames: ["that", "date", "index"],
      );

  @override
  String crateApiFocusHubFocusHubExportJson({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubExportJsonConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubExportJsonConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_export_json",
        argNames: ["that"],
      );

  @override
  List<DayTodos> crateApiFocusHubFocusHubHistoryBefore({
    required FocusHub that,
    required String date,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_day_todos,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubHistoryBeforeConstMeta,
        argValues: [that, date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubHistoryBeforeConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_history_before",
        argNames: ["that", "date"],
      );

  @override
  ImportSummary crateApiFocusHubFocusHubImportJson({
    required FocusHub that,
    required String json,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_String(json, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_import_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubImportJsonConstMeta,
        argValues: [that, json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubImportJsonConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_import_json",
        argNames: ["that", "json"],
      );

  @override
  String? crateApiFocusHubFocusHubLoadWarning({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubFocusHubLoadWarningConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubLoadWarningConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_load_warning",
        argNames: ["that"],
      );

  @override
  FocusHub crateApiFocusHubFocusHubOpen({required String dataDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubOpenConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubOpenConstMeta =>
      const TaskConstMeta(debugName: "FocusHub_open", argNames: ["dataDir"]);

  @override
  void crateApiFocusHubFocusHubResetTimer({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubResetTimerConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubResetTimerConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_reset_timer",
        argNames: ["that"],
      );

  @override
  List<RewardView> crateApiFocusHubFocusHubRewards({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_reward_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubFocusHubRewardsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubRewardsConstMeta =>
      const TaskConstMeta(debugName: "FocusHub_rewards", argNames: ["that"]);

  @override
  void crateApiFocusHubFocusHubSave({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubSaveConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubSaveConstMeta =>
      const TaskConstMeta(debugName: "FocusHub_save", argNames: ["that"]);

  @override
  void crateApiFocusHubFocusHubSetBackground({
    required FocusHub that,
    required String fileName,
    required List<int> bytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_String(fileName, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubSetBackgroundConstMeta,
        argValues: [that, fileName, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubSetBackgroundConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_set_background",
        argNames: ["that", "fileName", "bytes"],
      );

  @override
  void crateApiFocusHubFocusHubSetRewardCompleted({
    required FocusHub that,
    required int index,
    required bool completed,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_u_32(index, serializer);
          sse_encode_bool(completed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubSetRewardCompletedConstMeta,
        argValues: [that, index, completed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubSetRewardCompletedConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_set_reward_completed",
        argNames: ["that", "index", "completed"],
      );

  @override
  void crateApiFocusHubFocusHubSetTimeZone({
    required FocusHub that,
    int? offsetHours,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_opt_box_autoadd_i_32(offsetHours, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubSetTimeZoneConstMeta,
        argValues: [that, offsetHours],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubSetTimeZoneConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_set_time_zone",
        argNames: ["that", "offsetHours"],
      );

  @override
  void crateApiFocusHubFocusHubSetTimerSettings({
    required FocusHub that,
    required int workSecs,
    required int breakSecs,
    required int loops,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_u_32(workSecs, serializer);
          sse_encode_u_32(breakSecs, serializer);
          sse_encode_u_32(loops, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubSetTimerSettingsConstMeta,
        argValues: [that, workSecs, breakSecs, loops],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubSetTimerSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_set_timer_settings",
        argNames: ["that", "workSecs", "breakSecs", "loops"],
      );

  @override
  void crateApiFocusHubFocusHubSetTodoCompleted({
    required FocusHub that,
    required String date,
    required int index,
    required bool completed,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          sse_encode_u_32(index, serializer);
          sse_encode_bool(completed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubSetTodoCompletedConstMeta,
        argValues: [that, date, index, completed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubSetTodoCompletedConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_set_todo_completed",
        argNames: ["that", "date", "index", "completed"],
      );

  @override
  StatsView crateApiFocusHubFocusHubStats({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stats_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubFocusHubStatsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubStatsConstMeta =>
      const TaskConstMeta(debugName: "FocusHub_stats", argNames: ["that"]);

  @override
  List<SessionAlert> crateApiFocusHubFocusHubTick({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_session_alert,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubTickConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubTickConstMeta =>
      const TaskConstMeta(debugName: "FocusHub_tick", argNames: ["that"]);

  @override
  TimeZoneView crateApiFocusHubFocusHubTimeZone({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_time_zone_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubFocusHubTimeZoneConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubTimeZoneConstMeta =>
      const TaskConstMeta(debugName: "FocusHub_time_zone", argNames: ["that"]);

  @override
  TimerView crateApiFocusHubFocusHubTimerView({required FocusHub that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_timer_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubFocusHubTimerViewConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubTimerViewConstMeta =>
      const TaskConstMeta(debugName: "FocusHub_timer_view", argNames: ["that"]);

  @override
  List<TodoView> crateApiFocusHubFocusHubTodosFor({
    required FocusHub that,
    required String date,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          sse_encode_String(date, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_todo_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubTodosForConstMeta,
        argValues: [that, date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubTodosForConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_todos_for",
        argNames: ["that", "date"],
      );

  @override
  List<SessionAlert> crateApiFocusHubFocusHubToggleTimer({
    required FocusHub that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_session_alert,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubFocusHubToggleTimerConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubToggleTimerConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_toggle_timer",
        argNames: ["that"],
      );

  @override
  List<ScheduledAlert> crateApiFocusHubFocusHubUpcomingAlerts({
    required FocusHub that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_scheduled_alert,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubFocusHubUpcomingAlertsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubFocusHubUpcomingAlertsConstMeta =>
      const TaskConstMeta(
        debugName: "FocusHub_upcoming_alerts",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  String crateApiFocusHubLongDate({required String date}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(date, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubLongDateConstMeta,
        argValues: [date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubLongDateConstMeta =>
      const TaskConstMeta(debugName: "long_date", argNames: ["date"]);

  @override
  YearMonth crateApiFocusHubMonthOf({required String date}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(date, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_year_month,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusHubMonthOfConstMeta,
        argValues: [date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubMonthOfConstMeta =>
      const TaskConstMeta(debugName: "month_of", argNames: ["date"]);

  @override
  YearMonth crateApiFocusHubShiftMonth({
    required int year,
    required int month,
    required int delta,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(year, serializer);
          sse_encode_u_32(month, serializer);
          sse_encode_i_32(delta, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_year_month,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubShiftMonthConstMeta,
        argValues: [year, month, delta],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubShiftMonthConstMeta => const TaskConstMeta(
    debugName: "shift_month",
    argNames: ["year", "month", "delta"],
  );

  @override
  String crateApiFocusHubTodayDate() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusHubTodayDateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusHubTodayDateConstMeta =>
      const TaskConstMeta(debugName: "today_date", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FocusHub => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FocusHub => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  FocusHub
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FocusHubImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FocusHub
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FocusHubImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FocusHub
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FocusHubImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FocusHub
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FocusHubImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CalendarDay dco_decode_calendar_day(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CalendarDay(
      day: dco_decode_u_32(arr[0]),
      date: dco_decode_String(arr[1]),
      isToday: dco_decode_bool(arr[2]),
      isSelected: dco_decode_bool(arr[3]),
      hasTodos: dco_decode_bool(arr[4]),
    );
  }

  @protected
  CalendarMonth dco_decode_calendar_month(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CalendarMonth(
      title: dco_decode_String(arr[0]),
      year: dco_decode_i_32(arr[1]),
      month: dco_decode_u_32(arr[2]),
      leadingBlanks: dco_decode_u_32(arr[3]),
      days: dco_decode_list_calendar_day(arr[4]),
    );
  }

  @protected
  DayTodos dco_decode_day_todos(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DayTodos(
      date: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      todos: dco_decode_list_todo_view(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImportSummary dco_decode_import_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ImportSummary(
      days: dco_decode_u_32(arr[0]),
      tasks: dco_decode_u_32(arr[1]),
      rewards: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  List<CalendarDay> dco_decode_list_calendar_day(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_calendar_day).toList();
  }

  @protected
  List<DayTodos> dco_decode_list_day_todos(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_day_todos).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RewardView> dco_decode_list_reward_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reward_view).toList();
  }

  @protected
  List<ScheduledAlert> dco_decode_list_scheduled_alert(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_scheduled_alert).toList();
  }

  @protected
  List<SessionAlert> dco_decode_list_session_alert(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_session_alert).toList();
  }

  @protected
  List<TodoView> dco_decode_list_todo_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_todo_view).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  RewardView dco_decode_reward_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RewardView(
      index: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      completed: dco_decode_bool(arr[2]),
    );
  }

  @protected
  ScheduledAlert dco_decode_scheduled_alert(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ScheduledAlert(
      delayMs: dco_decode_u_32(arr[0]),
      title: dco_decode_String(arr[1]),
      body: dco_decode_String(arr[2]),
    );
  }

  @protected
  SessionAlert dco_decode_session_alert(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SessionAlert(
      title: dco_decode_String(arr[0]),
      body: dco_decode_String(arr[1]),
    );
  }

  @protected
  StatsView dco_decode_stats_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StatsView(
      totalTime: dco_decode_String(arr[0]),
      todaySessions: dco_decode_u_32(arr[1]),
      todayTime: dco_decode_String(arr[2]),
      monthSessions: dco_decode_u_32(arr[3]),
      monthName: dco_decode_String(arr[4]),
    );
  }

  @protected
  TimeZoneView dco_decode_time_zone_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TimeZoneView(
      followsDevice: dco_decode_bool(arr[0]),
      offsetHours: dco_decode_i_32(arr[1]),
      label: dco_decode_String(arr[2]),
    );
  }

  @protected
  TimerView dco_decode_timer_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return TimerView(
      isWork: dco_decode_bool(arr[0]),
      isRunning: dco_decode_bool(arr[1]),
      modeLabel: dco_decode_String(arr[2]),
      loopLabel: dco_decode_String(arr[3]),
      remaining: dco_decode_String(arr[4]),
      progress: dco_decode_f_64(arr[5]),
      workSecs: dco_decode_u_32(arr[6]),
      breakSecs: dco_decode_u_32(arr[7]),
      loops: dco_decode_u_32(arr[8]),
    );
  }

  @protected
  TodoView dco_decode_todo_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TodoView(
      index: dco_decode_u_32(arr[0]),
      text: dco_decode_String(arr[1]),
      completed: dco_decode_bool(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  YearMonth dco_decode_year_month(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return YearMonth(
      year: dco_decode_i_32(arr[0]),
      month: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  FocusHub
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FocusHubImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FocusHub
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FocusHubImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FocusHub
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FocusHubImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FocusHub
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FocusHubImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  CalendarDay sse_decode_calendar_day(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_day = sse_decode_u_32(deserializer);
    var var_date = sse_decode_String(deserializer);
    var var_isToday = sse_decode_bool(deserializer);
    var var_isSelected = sse_decode_bool(deserializer);
    var var_hasTodos = sse_decode_bool(deserializer);
    return CalendarDay(
      day: var_day,
      date: var_date,
      isToday: var_isToday,
      isSelected: var_isSelected,
      hasTodos: var_hasTodos,
    );
  }

  @protected
  CalendarMonth sse_decode_calendar_month(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_year = sse_decode_i_32(deserializer);
    var var_month = sse_decode_u_32(deserializer);
    var var_leadingBlanks = sse_decode_u_32(deserializer);
    var var_days = sse_decode_list_calendar_day(deserializer);
    return CalendarMonth(
      title: var_title,
      year: var_year,
      month: var_month,
      leadingBlanks: var_leadingBlanks,
      days: var_days,
    );
  }

  @protected
  DayTodos sse_decode_day_todos(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_date = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_todos = sse_decode_list_todo_view(deserializer);
    return DayTodos(date: var_date, title: var_title, todos: var_todos);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImportSummary sse_decode_import_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_days = sse_decode_u_32(deserializer);
    var var_tasks = sse_decode_u_32(deserializer);
    var var_rewards = sse_decode_u_32(deserializer);
    return ImportSummary(
      days: var_days,
      tasks: var_tasks,
      rewards: var_rewards,
    );
  }

  @protected
  List<CalendarDay> sse_decode_list_calendar_day(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CalendarDay>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_calendar_day(deserializer));
    }
    return ans_;
  }

  @protected
  List<DayTodos> sse_decode_list_day_todos(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DayTodos>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_day_todos(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RewardView> sse_decode_list_reward_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RewardView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reward_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<ScheduledAlert> sse_decode_list_scheduled_alert(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ScheduledAlert>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_scheduled_alert(deserializer));
    }
    return ans_;
  }

  @protected
  List<SessionAlert> sse_decode_list_session_alert(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SessionAlert>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_session_alert(deserializer));
    }
    return ans_;
  }

  @protected
  List<TodoView> sse_decode_list_todo_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TodoView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_todo_view(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RewardView sse_decode_reward_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_completed = sse_decode_bool(deserializer);
    return RewardView(
      index: var_index,
      name: var_name,
      completed: var_completed,
    );
  }

  @protected
  ScheduledAlert sse_decode_scheduled_alert(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_delayMs = sse_decode_u_32(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    return ScheduledAlert(
      delayMs: var_delayMs,
      title: var_title,
      body: var_body,
    );
  }

  @protected
  SessionAlert sse_decode_session_alert(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    return SessionAlert(title: var_title, body: var_body);
  }

  @protected
  StatsView sse_decode_stats_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalTime = sse_decode_String(deserializer);
    var var_todaySessions = sse_decode_u_32(deserializer);
    var var_todayTime = sse_decode_String(deserializer);
    var var_monthSessions = sse_decode_u_32(deserializer);
    var var_monthName = sse_decode_String(deserializer);
    return StatsView(
      totalTime: var_totalTime,
      todaySessions: var_todaySessions,
      todayTime: var_todayTime,
      monthSessions: var_monthSessions,
      monthName: var_monthName,
    );
  }

  @protected
  TimeZoneView sse_decode_time_zone_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_followsDevice = sse_decode_bool(deserializer);
    var var_offsetHours = sse_decode_i_32(deserializer);
    var var_label = sse_decode_String(deserializer);
    return TimeZoneView(
      followsDevice: var_followsDevice,
      offsetHours: var_offsetHours,
      label: var_label,
    );
  }

  @protected
  TimerView sse_decode_timer_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isWork = sse_decode_bool(deserializer);
    var var_isRunning = sse_decode_bool(deserializer);
    var var_modeLabel = sse_decode_String(deserializer);
    var var_loopLabel = sse_decode_String(deserializer);
    var var_remaining = sse_decode_String(deserializer);
    var var_progress = sse_decode_f_64(deserializer);
    var var_workSecs = sse_decode_u_32(deserializer);
    var var_breakSecs = sse_decode_u_32(deserializer);
    var var_loops = sse_decode_u_32(deserializer);
    return TimerView(
      isWork: var_isWork,
      isRunning: var_isRunning,
      modeLabel: var_modeLabel,
      loopLabel: var_loopLabel,
      remaining: var_remaining,
      progress: var_progress,
      workSecs: var_workSecs,
      breakSecs: var_breakSecs,
      loops: var_loops,
    );
  }

  @protected
  TodoView sse_decode_todo_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_completed = sse_decode_bool(deserializer);
    return TodoView(index: var_index, text: var_text, completed: var_completed);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  YearMonth sse_decode_year_month(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_year = sse_decode_i_32(deserializer);
    var var_month = sse_decode_u_32(deserializer);
    return YearMonth(year: var_year, month: var_month);
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    FocusHub self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FocusHubImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    FocusHub self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FocusHubImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    FocusHub self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FocusHubImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFocusHub(
    FocusHub self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FocusHubImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_calendar_day(CalendarDay self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.day, serializer);
    sse_encode_String(self.date, serializer);
    sse_encode_bool(self.isToday, serializer);
    sse_encode_bool(self.isSelected, serializer);
    sse_encode_bool(self.hasTodos, serializer);
  }

  @protected
  void sse_encode_calendar_month(CalendarMonth self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_i_32(self.year, serializer);
    sse_encode_u_32(self.month, serializer);
    sse_encode_u_32(self.leadingBlanks, serializer);
    sse_encode_list_calendar_day(self.days, serializer);
  }

  @protected
  void sse_encode_day_todos(DayTodos self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.date, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_todo_view(self.todos, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_import_summary(ImportSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.days, serializer);
    sse_encode_u_32(self.tasks, serializer);
    sse_encode_u_32(self.rewards, serializer);
  }

  @protected
  void sse_encode_list_calendar_day(
    List<CalendarDay> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_calendar_day(item, serializer);
    }
  }

  @protected
  void sse_encode_list_day_todos(
    List<DayTodos> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_day_todos(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_reward_view(
    List<RewardView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reward_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_scheduled_alert(
    List<ScheduledAlert> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_scheduled_alert(item, serializer);
    }
  }

  @protected
  void sse_encode_list_session_alert(
    List<SessionAlert> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_session_alert(item, serializer);
    }
  }

  @protected
  void sse_encode_list_todo_view(
    List<TodoView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_todo_view(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_reward_view(RewardView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.completed, serializer);
  }

  @protected
  void sse_encode_scheduled_alert(
    ScheduledAlert self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.delayMs, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.body, serializer);
  }

  @protected
  void sse_encode_session_alert(SessionAlert self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.body, serializer);
  }

  @protected
  void sse_encode_stats_view(StatsView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.totalTime, serializer);
    sse_encode_u_32(self.todaySessions, serializer);
    sse_encode_String(self.todayTime, serializer);
    sse_encode_u_32(self.monthSessions, serializer);
    sse_encode_String(self.monthName, serializer);
  }

  @protected
  void sse_encode_time_zone_view(TimeZoneView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.followsDevice, serializer);
    sse_encode_i_32(self.offsetHours, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_timer_view(TimerView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isWork, serializer);
    sse_encode_bool(self.isRunning, serializer);
    sse_encode_String(self.modeLabel, serializer);
    sse_encode_String(self.loopLabel, serializer);
    sse_encode_String(self.remaining, serializer);
    sse_encode_f_64(self.progress, serializer);
    sse_encode_u_32(self.workSecs, serializer);
    sse_encode_u_32(self.breakSecs, serializer);
    sse_encode_u_32(self.loops, serializer);
  }

  @protected
  void sse_encode_todo_view(TodoView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_bool(self.completed, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_year_month(YearMonth self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.year, serializer);
    sse_encode_u_32(self.month, serializer);
  }
}

@sealed
class FocusHubImpl extends RustOpaque implements FocusHub {
  // Not to be used by end users
  FocusHubImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FocusHubImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FocusHub,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FocusHub,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FocusHubPtr,
  );

  void addReward({required String name}) => RustLib.instance.api
      .crateApiFocusHubFocusHubAddReward(that: this, name: name);

  void addTodo({required String date, required String text}) => RustLib
      .instance
      .api
      .crateApiFocusHubFocusHubAddTodo(that: this, date: date, text: text);

  /// The custom background image's path, or `null` for the built-in one.
  String? backgroundPath() =>
      RustLib.instance.api.crateApiFocusHubFocusHubBackgroundPath(that: this);

  CalendarMonth calendarMonth({
    required int year,
    required int month,
    required String selectedDate,
  }) => RustLib.instance.api.crateApiFocusHubFocusHubCalendarMonth(
    that: this,
    year: year,
    month: month,
    selectedDate: selectedDate,
  );

  void clearBackground() =>
      RustLib.instance.api.crateApiFocusHubFocusHubClearBackground(that: this);

  /// The time for the clock, "14:05:09", in the chosen time zone.
  String clockText() =>
      RustLib.instance.api.crateApiFocusHubFocusHubClockText(that: this);

  String dataFile() =>
      RustLib.instance.api.crateApiFocusHubFocusHubDataFile(that: this);

  void deleteReward({required int index}) => RustLib.instance.api
      .crateApiFocusHubFocusHubDeleteReward(that: this, index: index);

  void deleteTodo({required String date, required int index}) => RustLib
      .instance
      .api
      .crateApiFocusHubFocusHubDeleteTodo(that: this, date: date, index: index);

  /// All data as JSON (the desktop app's `focushub_data.json` format).
  String exportJson() =>
      RustLib.instance.api.crateApiFocusHubFocusHubExportJson(that: this);

  /// Days before `date` with tasks, newest first.
  List<DayTodos> historyBefore({required String date}) => RustLib.instance.api
      .crateApiFocusHubFocusHubHistoryBefore(that: this, date: date);

  /// Replaces tasks, stats and rewards with those in a `focushub_data.json` file.
  ImportSummary importJson({required String json}) => RustLib.instance.api
      .crateApiFocusHubFocusHubImportJson(that: this, json: json);

  /// A message to show once if the saved data was damaged, otherwise `null`.
  String? loadWarning() =>
      RustLib.instance.api.crateApiFocusHubFocusHubLoadWarning(that: this);

  void resetTimer() =>
      RustLib.instance.api.crateApiFocusHubFocusHubResetTimer(that: this);

  List<RewardView> rewards() =>
      RustLib.instance.api.crateApiFocusHubFocusHubRewards(that: this);

  void save() => RustLib.instance.api.crateApiFocusHubFocusHubSave(that: this);

  /// Saves a copy of a chosen image (GIF, PNG, JPG or WebP) as the background.
  void setBackground({required String fileName, required List<int> bytes}) =>
      RustLib.instance.api.crateApiFocusHubFocusHubSetBackground(
        that: this,
        fileName: fileName,
        bytes: bytes,
      );

  void setRewardCompleted({required int index, required bool completed}) =>
      RustLib.instance.api.crateApiFocusHubFocusHubSetRewardCompleted(
        that: this,
        index: index,
        completed: completed,
      );

  /// `null` follows the device's time zone; otherwise hours from GMT (-12 to 14).
  void setTimeZone({int? offsetHours}) =>
      RustLib.instance.api.crateApiFocusHubFocusHubSetTimeZone(
        that: this,
        offsetHours: offsetHours,
      );

  /// Changes the session lengths and loops (this resets the timer). Values are limited
  /// like the desktop app: work up to 120m 59s, break up to 60m 59s, 1 to 20 loops.
  void setTimerSettings({
    required int workSecs,
    required int breakSecs,
    required int loops,
  }) => RustLib.instance.api.crateApiFocusHubFocusHubSetTimerSettings(
    that: this,
    workSecs: workSecs,
    breakSecs: breakSecs,
    loops: loops,
  );

  void setTodoCompleted({
    required String date,
    required int index,
    required bool completed,
  }) => RustLib.instance.api.crateApiFocusHubFocusHubSetTodoCompleted(
    that: this,
    date: date,
    index: index,
    completed: completed,
  );

  StatsView stats() =>
      RustLib.instance.api.crateApiFocusHubFocusHubStats(that: this);

  /// Call often (a few times a second). Returns the sessions that just ended.
  List<SessionAlert> tick() =>
      RustLib.instance.api.crateApiFocusHubFocusHubTick(that: this);

  TimeZoneView timeZone() =>
      RustLib.instance.api.crateApiFocusHubFocusHubTimeZone(that: this);

  TimerView timerView() =>
      RustLib.instance.api.crateApiFocusHubFocusHubTimerView(that: this);

  List<TodoView> todosFor({required String date}) => RustLib.instance.api
      .crateApiFocusHubFocusHubTodosFor(that: this, date: date);

  /// Start or pause. Returns any sessions that ended right before pausing.
  List<SessionAlert> toggleTimer() =>
      RustLib.instance.api.crateApiFocusHubFocusHubToggleTimer(that: this);

  /// Every session end still to come, if the timer keeps running.
  List<ScheduledAlert> upcomingAlerts() =>
      RustLib.instance.api.crateApiFocusHubFocusHubUpcomingAlerts(that: this);
}
