// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `alert`, `now_ms`, `today`, `todo_views`

/// Today's date on this device.
String todayDate() => RustLib.instance.api.crateApiFocusHubTodayDate();

/// "Saturday, September 26, 2026"
String longDate({required String date}) =>
    RustLib.instance.api.crateApiFocusHubLongDate(date: date);

YearMonth monthOf({required String date}) =>
    RustLib.instance.api.crateApiFocusHubMonthOf(date: date);

/// `delta` months after (or before, if negative) the given month.
YearMonth shiftMonth({
  required int year,
  required int month,
  required int delta,
}) => RustLib.instance.api.crateApiFocusHubShiftMonth(
  year: year,
  month: month,
  delta: delta,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FocusHub>>
abstract class FocusHub implements RustOpaqueInterface {
  void addReward({required String name});

  void addTodo({required String date, required String text});

  /// The custom background image's path, or `null` for the built-in one.
  String? backgroundPath();

  CalendarMonth calendarMonth({
    required int year,
    required int month,
    required String selectedDate,
  });

  void clearBackground();

  /// The time for the clock, "14:05:09", in the chosen time zone.
  String clockText();

  String dataFile();

  void deleteReward({required int index});

  void deleteTodo({required String date, required int index});

  /// All data as JSON (the desktop app's `focushub_data.json` format).
  String exportJson();

  /// Days before `date` with tasks, newest first.
  List<DayTodos> historyBefore({required String date});

  /// Replaces tasks, stats and rewards with those in a `focushub_data.json` file.
  ImportSummary importJson({required String json});

  /// A message to show once if the saved data was damaged, otherwise `null`.
  String? loadWarning();

  /// Opens the saved data in `data_dir` (the app's private folder).
  static FocusHub open({required String dataDir}) =>
      RustLib.instance.api.crateApiFocusHubFocusHubOpen(dataDir: dataDir);

  void resetTimer();

  List<RewardView> rewards();

  void save();

  /// Saves a copy of a chosen image (GIF, PNG, JPG or WebP) as the background.
  void setBackground({required String fileName, required List<int> bytes});

  void setRewardCompleted({required int index, required bool completed});

  /// `null` follows the device's time zone; otherwise hours from GMT (-12 to 14).
  void setTimeZone({int? offsetHours});

  /// Changes the session lengths and loops (this resets the timer). Values are limited
  /// like the desktop app: work up to 120m 59s, break up to 60m 59s, 1 to 20 loops.
  void setTimerSettings({
    required int workSecs,
    required int breakSecs,
    required int loops,
  });

  void setTodoCompleted({
    required String date,
    required int index,
    required bool completed,
  });

  StatsView stats();

  /// Call often (a few times a second). Returns the sessions that just ended.
  List<SessionAlert> tick();

  TimeZoneView timeZone();

  TimerView timerView();

  List<TodoView> todosFor({required String date});

  /// Start or pause. Returns any sessions that ended right before pausing.
  List<SessionAlert> toggleTimer();

  /// Every session end still to come, if the timer keeps running.
  List<ScheduledAlert> upcomingAlerts();
}

class CalendarDay {
  final int day;
  final String date;
  final bool isToday;
  final bool isSelected;
  final bool hasTodos;

  const CalendarDay({
    required this.day,
    required this.date,
    required this.isToday,
    required this.isSelected,
    required this.hasTodos,
  });

  @override
  int get hashCode =>
      day.hashCode ^
      date.hashCode ^
      isToday.hashCode ^
      isSelected.hashCode ^
      hasTodos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarDay &&
          runtimeType == other.runtimeType &&
          day == other.day &&
          date == other.date &&
          isToday == other.isToday &&
          isSelected == other.isSelected &&
          hasTodos == other.hasTodos;
}

class CalendarMonth {
  /// "September 2026"
  final String title;
  final int year;
  final int month;

  /// Empty cells before day 1 (weeks start on Monday).
  final int leadingBlanks;
  final List<CalendarDay> days;

  const CalendarMonth({
    required this.title,
    required this.year,
    required this.month,
    required this.leadingBlanks,
    required this.days,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      year.hashCode ^
      month.hashCode ^
      leadingBlanks.hashCode ^
      days.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarMonth &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          year == other.year &&
          month == other.month &&
          leadingBlanks == other.leadingBlanks &&
          days == other.days;
}

class DayTodos {
  final String date;

  /// "Friday, September 25"
  final String title;
  final List<TodoView> todos;

  const DayTodos({
    required this.date,
    required this.title,
    required this.todos,
  });

  @override
  int get hashCode => date.hashCode ^ title.hashCode ^ todos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DayTodos &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          title == other.title &&
          todos == other.todos;
}

class ImportSummary {
  final int days;
  final int tasks;
  final int rewards;

  const ImportSummary({
    required this.days,
    required this.tasks,
    required this.rewards,
  });

  @override
  int get hashCode => days.hashCode ^ tasks.hashCode ^ rewards.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportSummary &&
          runtimeType == other.runtimeType &&
          days == other.days &&
          tasks == other.tasks &&
          rewards == other.rewards;
}

class RewardView {
  final int index;
  final String name;
  final bool completed;

  const RewardView({
    required this.index,
    required this.name,
    required this.completed,
  });

  @override
  int get hashCode => index.hashCode ^ name.hashCode ^ completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RewardView &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          completed == other.completed;
}

/// A session end still to come, for scheduling a notification.
class ScheduledAlert {
  final int delayMs;
  final String title;
  final String body;

  const ScheduledAlert({
    required this.delayMs,
    required this.title,
    required this.body,
  });

  @override
  int get hashCode => delayMs.hashCode ^ title.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScheduledAlert &&
          runtimeType == other.runtimeType &&
          delayMs == other.delayMs &&
          title == other.title &&
          body == other.body;
}

/// A session just ended.
class SessionAlert {
  final String title;
  final String body;

  const SessionAlert({required this.title, required this.body});

  @override
  int get hashCode => title.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionAlert &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          body == other.body;
}

class StatsView {
  /// "0d 3h 20m 5s"
  final String totalTime;
  final int todaySessions;

  /// "01:02:03"
  final String todayTime;
  final int monthSessions;

  /// "September"
  final String monthName;

  const StatsView({
    required this.totalTime,
    required this.todaySessions,
    required this.todayTime,
    required this.monthSessions,
    required this.monthName,
  });

  @override
  int get hashCode =>
      totalTime.hashCode ^
      todaySessions.hashCode ^
      todayTime.hashCode ^
      monthSessions.hashCode ^
      monthName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsView &&
          runtimeType == other.runtimeType &&
          totalTime == other.totalTime &&
          todaySessions == other.todaySessions &&
          todayTime == other.todayTime &&
          monthSessions == other.monthSessions &&
          monthName == other.monthName;
}

class TimeZoneView {
  final bool followsDevice;

  /// The chosen offset (only meaningful when not following the device).
  final int offsetHours;

  /// "Device (GMT+07:00)" or "GMT+05:00"
  final String label;

  const TimeZoneView({
    required this.followsDevice,
    required this.offsetHours,
    required this.label,
  });

  @override
  int get hashCode =>
      followsDevice.hashCode ^ offsetHours.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeZoneView &&
          runtimeType == other.runtimeType &&
          followsDevice == other.followsDevice &&
          offsetHours == other.offsetHours &&
          label == other.label;
}

class TimerView {
  final bool isWork;
  final bool isRunning;

  /// "Study Time" or "Break Time"
  final String modeLabel;

  /// "(1/4)"
  final String loopLabel;

  /// "59:59"
  final String remaining;

  /// 0.0 to 1.0
  final double progress;
  final int workSecs;
  final int breakSecs;
  final int loops;

  const TimerView({
    required this.isWork,
    required this.isRunning,
    required this.modeLabel,
    required this.loopLabel,
    required this.remaining,
    required this.progress,
    required this.workSecs,
    required this.breakSecs,
    required this.loops,
  });

  @override
  int get hashCode =>
      isWork.hashCode ^
      isRunning.hashCode ^
      modeLabel.hashCode ^
      loopLabel.hashCode ^
      remaining.hashCode ^
      progress.hashCode ^
      workSecs.hashCode ^
      breakSecs.hashCode ^
      loops.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimerView &&
          runtimeType == other.runtimeType &&
          isWork == other.isWork &&
          isRunning == other.isRunning &&
          modeLabel == other.modeLabel &&
          loopLabel == other.loopLabel &&
          remaining == other.remaining &&
          progress == other.progress &&
          workSecs == other.workSecs &&
          breakSecs == other.breakSecs &&
          loops == other.loops;
}

class TodoView {
  /// Position in that day's list (use it to change or delete the task).
  final int index;
  final String text;
  final bool completed;

  const TodoView({
    required this.index,
    required this.text,
    required this.completed,
  });

  @override
  int get hashCode => index.hashCode ^ text.hashCode ^ completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoView &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          text == other.text &&
          completed == other.completed;
}

class YearMonth {
  final int year;
  final int month;

  const YearMonth({required this.year, required this.month});

  @override
  int get hashCode => year.hashCode ^ month.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YearMonth &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          month == other.month;
}
